SHELL=/bin/bash

SCRIPT_FILENAME = ckb
SCRIPT_INSTALLATION_DIRECTORY = /usr/bin
SCRIPT_INSTALLATION_PATH = ${SCRIPT_INSTALLATION_DIRECTORY}/${SCRIPT_FILENAME}

MAN_FILENAME = ${SCRIPT_FILENAME}.1
MAN_INSTALLATION_DIRECTORY = /usr/local/man/man1
MAN_INSTALLATION_PATH = ${MAN_INSTALLATION_DIRECTORY}/${MAN_FILENAME}

install:
	@sudo cp ${SCRIPT_FILENAME} "${SCRIPT_INSTALLATION_PATH}"
	@sudo chmod ugo+x "${SCRIPT_INSTALLATION_PATH}"
	@sudo cp "${MAN_FILENAME}" "${MAN_INSTALLATION_PATH}"
	@sudo chmod ugo+r "${MAN_INSTALLATION_PATH}"

man:
	@groff -Tascii -man "${MAN_FILENAME}" | more

clean:
	@sudo rm -f "${SCRIPT_INSTALLATION_PATH}"
	@sudo rm -f "${MAN_INSTALLATION_PATH}"
